const KEY='cambridge-b2-academy-progress-v1';
const defaultState={xp:0,completed:0,modules:{writing:0,reading:0,useofenglish:0,vocabulary:0,connectors:0},indices:{writing:0,reading:0,uoe:0,connectors:0,vocabQuiz:0},writingDrafts:{},diagnostic:null};
let state=loadState();
function loadState(){try{const old=JSON.parse(localStorage.getItem(KEY)||'{}');return {...defaultState,...old,modules:{...defaultState.modules,...(old.modules||{})},indices:{...defaultState.indices,...(old.indices||{})},writingDrafts:{...(old.writingDrafts||{})}}}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(KEY,JSON.stringify(state));renderDashboard()}
function completePractice(module,xp){state.modules[module]=(state.modules[module]||0)+1;state.completed+=1;state.xp+=xp;saveState()}
function renderDashboard(){xpValue.textContent=state.xp;completedValue.textContent=state.completed;accuracyValue.textContent=state.diagnostic?`${state.diagnostic.score}/${state.diagnostic.total}`:'—';levelValue.textContent=state.diagnostic?state.diagnostic.label:'Not tested';diagnosticBadge.textContent=state.diagnostic?'Completed':'Not completed';Object.entries(state.modules).forEach(([k,v])=>{const el=document.getElementById(`${k}Badge`);if(el)el.textContent=`${v} practice${v===1?'':'s'}`})}
function openScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.open===id));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openScreen(b.dataset.open)));

const diagnostic=[
['The course was cancelled ___ a lack of participants.',['because','because of','although'],1],
['I wish I ___ more time to prepare yesterday.',['had had','would have','have had'],0],
['Hardly ___ the room when the lights went out.',['we had entered','had we entered','we entered'],1],
['The article suggests that the new policy may have an unexpected ___.',['affect','effect','effective'],1],
['She succeeded ___ convincing the team to change its plan.',['in','at','on'],0],
['The word closest to “reluctant” is…',['unwilling','delighted','certain'],0],
['Choose the best transformation: “It wasn’t necessary for Mia to come early.”',['Mia mustn’t come early.','Mia needn’t have come early.','Mia didn’t need come early.'],1],
['Choose the best connector: “The plan was expensive; ___, it produced excellent results.”',['however','therefore','in addition'],0],
['“To take something for granted” means…',['to appreciate it deeply','to assume it will always be available','to borrow it temporarily'],1],
['If the writer says a result was “far from conclusive”, it was…',['completely certain','not decisive','very surprising'],1],
['The correct form is: “The project was completed ___ than expected.”',['more quickly','quickerly','most quickly'],0],
['Choose the most natural phrase: “The experience ___ a lasting impression on me.”',['did','made','had'],1]
];
function renderDiagnostic(){diagnosticQuiz.innerHTML=diagnostic.map((q,i)=>`<fieldset class="panel"><legend>${i+1}. ${q[0]}</legend>${q[1].map((o,j)=>`<label><input type="radio" name="d${i}" value="${j}"> ${o}</label>`).join('')}</fieldset>`).join('');diagnosticFeedback.textContent=''}
checkDiagnostic.addEventListener('click',()=>{const fd=new FormData(diagnosticQuiz);let score=0;diagnostic.forEach((q,i)=>{if(Number(fd.get(`d${i}`))===q[2])score++});let label='B1 foundation';if(score>=10)label='Strong B2 signal';else if(score>=7)label='Developing B2';else if(score>=4)label='Upper B1';state.diagnostic={score,total:diagnostic.length,label};state.xp+=50;saveState();diagnosticFeedback.className='feedback success';diagnosticFeedback.textContent=`${score}/${diagnostic.length}. Level signal: ${label}. This is a practice indicator, not an official result.`});

const writingChallenges=[
{type:'ESSAY · 140–190 WORDS',title:'Homework and free time',prompt:'<p>Some people believe teenagers should receive less homework so they can have more free time.</p><p>Write an essay discussing:</p><ul><li>academic progress;</li><li>health and wellbeing;</li><li>your own idea.</li></ul>',phrases:'On the one hand… · Nevertheless… · A further point to consider is… · To sum up…',placeholder:'Many people argue that...',model:'<h3>Model structure</h3><p><strong>Introduction:</strong> paraphrase the question and state the issue.</p><p><strong>Paragraph 2:</strong> discuss academic progress with a reason and example.</p><p><strong>Paragraph 3:</strong> discuss wellbeing and your own idea.</p><p><strong>Conclusion:</strong> give a clear final opinion.</p>'},
{type:'EMAIL · 140–190 WORDS',title:'A special place',prompt:'<p>Your English-speaking friend is doing a project about places that are special to people.</p><p>Write an email explaining:</p><ul><li>where the place is;</li><li>what it looks like;</li><li>why it matters to you.</li></ul>',phrases:'What makes this place special is… · It is located… · Whenever I go there…',placeholder:'Hi Sam,\n\nThanks for your message...',model:'<h3>Model idea</h3><p>Choose one real place, describe two or three visible details, then explain the emotional meaning with a specific memory.</p>'},
{type:'REVIEW · 140–190 WORDS',title:'A shop for teenagers',prompt:'<p>Write a review of a clothes shop for teenagers. Include:</p><ul><li>what the shop looks like;</li><li>the kind of clothes it sells;</li><li>the shop assistants;</li><li>whether you recommend it.</li></ul>',phrases:'What immediately stands out is… · The range includes… · I would definitely recommend…',placeholder:'Looking for a place to...',model:'<h3>Model structure</h3><p>Start with an engaging opening, describe the shop and service, evaluate both strengths and weaknesses, and finish with a clear recommendation.</p>'},
{type:'STORY · 140–190 WORDS',title:'The wrong suitcase',prompt:'<p>Begin with:</p><p><strong>Tom got off the train and, as it left, he realised he was holding the wrong suitcase.</strong></p><p>Your story must include an address and a surprise.</p>',phrases:'No sooner had… than… · To his surprise… · Eventually…',placeholder:'Tom got off the train and, as it left...',model:'<h3>Model idea</h3><p>Create one clear problem, reveal the address inside the case, build suspense, and end with a believable surprise.</p>'}
];
function renderWriting(){const i=state.indices.writing%writingChallenges.length,w=writingChallenges[i];writingTitle.textContent=w.title;writingCounter.textContent=`Challenge ${i+1} of ${writingChallenges.length}`;writingType.textContent=w.type;writingPromptTitle.textContent=w.title;writingPrompt.innerHTML=w.prompt;writingPhrases.textContent=w.phrases;writingText.placeholder=w.placeholder;writingText.value=state.writingDrafts[i]||'';modelAnswer.innerHTML=w.model;modelAnswer.classList.add('hidden');showModel.textContent='Show model';updateWordCount();writingFeedback.textContent=''}
function updateWordCount(){const n=(writingText.value.trim().match(/\b[\w’'-]+\b/g)||[]).length;wordCount.textContent=n;writingStatus.textContent=n<140?'Keep developing your ideas':n<=190?'Good B2 length':'Try to reduce repetition'}
writingText.addEventListener('input',()=>{state.writingDrafts[state.indices.writing%writingChallenges.length]=writingText.value;localStorage.setItem(KEY,JSON.stringify(state));updateWordCount()});
saveWriting.addEventListener('click',()=>{const n=Number(wordCount.textContent),checks=[...document.querySelectorAll('.write-check')].filter(x=>x.checked).length;if(n<120){writingFeedback.className='feedback error';writingFeedback.textContent='Develop the answer further. B2 tasks require 140–190 words.';return}if(checks<3){writingFeedback.className='feedback error';writingFeedback.textContent='Use the checklist before completing the practice.';return}completePractice('writing',50);writingFeedback.className='feedback success';writingFeedback.textContent='Practice completed. +50 XP. You can now compare your answer with the model guidance.'});
showModel.addEventListener('click',()=>{modelAnswer.classList.toggle('hidden');showModel.textContent=modelAnswer.classList.contains('hidden')?'Show model':'Hide model'});
nextWriting.addEventListener('click',()=>{state.indices.writing=(state.indices.writing+1)%writingChallenges.length;saveState();renderWriting()});

const readings=[
{title:'Why boredom may be useful',text:'<h3>Why boredom may be useful</h3><p>For years, boredom has been treated as something to avoid. Whenever people have a spare moment, many immediately reach for a phone. Yet several psychologists argue that constantly filling every pause may reduce creativity. When the mind is not occupied by a specific task, it often begins to make unexpected connections between ideas.</p><p>This does not mean that boredom is always pleasant or productive. Long periods without meaningful activity can be frustrating. However, short, quiet moments may allow people to reflect, solve problems and notice thoughts they would otherwise ignore.</p><p>Some schools have begun experimenting with brief periods of device-free silence. Teachers report that students initially resist the idea, but many later say they feel calmer and more focused. The aim is not to remove entertainment, but to help young people become more comfortable with moments that are not immediately stimulating.</p>',qs:[['What is the main point of the first paragraph?',['Phones are the main cause of boredom.','Avoiding every quiet moment may limit creativity.','Psychologists want people to stop using technology.'],1],['What does the writer say about boredom?',['It is always beneficial.','It can be useful in short periods.','It should be included in every lesson.'],1],['Why do some schools use device-free silence?',['To punish students','To improve comfort with unstimulating moments','To reduce homework'],1],['The writer’s attitude is best described as…',['balanced','strongly negative','uncritical'],0]]},
{title:'The rise of repair cafés',text:'<h3>The rise of repair cafés</h3><p>In many towns, people are gathering in community spaces to repair broken household objects instead of throwing them away. These events, known as repair cafés, are usually run by volunteers with practical skills. Visitors bring items such as lamps, small appliances and clothing, and work alongside the volunteers to fix them.</p><p>The environmental benefit is obvious: fewer objects end up in landfill. Yet organisers argue that the social effect is equally important. People who might never otherwise meet share knowledge, stories and sometimes frustration when a repair proves difficult. Even unsuccessful attempts can teach visitors how products are made and why some are harder to repair than others.</p><p>Critics point out that these events cannot solve the wider problem of cheaply manufactured goods. Organisers agree, but say that repair cafés still challenge the idea that replacing an object should always be the first response.</p>',qs:[['What do visitors usually do?',['Leave objects for professionals','Repair objects with volunteers','Buy replacement products'],1],['What additional benefit do organisers mention?',['Cheaper electricity','Social connection','Professional qualifications'],1],['What limitation do critics identify?',['The cafés are too expensive.','They cannot fix the wider production system.','Volunteers lack practical skills.'],1],['What do organisers believe repair cafés challenge?',['The habit of immediate replacement','The use of community spaces','The sale of cheap clothing'],0]]}
];
function renderReading(){const i=state.indices.reading%readings.length,r=readings[i];readingTitle.textContent=r.title;readingCounter.textContent=`Reading ${i+1} of ${readings.length}`;readingText.innerHTML=r.text;readingQuiz.innerHTML=r.qs.map((q,qi)=>`<fieldset class="panel"><legend>${qi+1}. ${q[0]}</legend>${q[1].map((o,oi)=>`<label><input type="radio" name="r${qi}" value="${oi}"> ${o}</label>`).join('')}</fieldset>`).join('');readingFeedback.textContent=''}
checkReading.addEventListener('click',()=>{const r=readings[state.indices.reading%readings.length],fd=new FormData(readingQuiz);let score=0;r.qs.forEach((q,i)=>{if(Number(fd.get(`r${i}`))===q[2])score++});if(score===r.qs.length){completePractice('reading',45);readingFeedback.className='feedback success';readingFeedback.textContent=`Perfect! ${score}/${r.qs.length}. +45 XP.`}else{readingFeedback.className='feedback error';readingFeedback.textContent=`You got ${score}/${r.qs.length}. Read again and look for evidence in the text.`}});
nextReading.addEventListener('click',()=>{state.indices.reading=(state.indices.reading+1)%readings.length;saveState();renderReading()});

const uoeSets=[
{title:'Open cloze',intro:'Complete each sentence with one word.',qs:[['I have lived here ___ 2022.',['since'],0],['She is not used ___ speaking in public.',['to'],0],['The film was much better ___ I expected.',['than'],0]]},
{title:'Word formation',intro:'Choose the correct form of the word in capitals.',qs:[['Her explanation was clear and very ___. (HELP)',['helpful','helpfully','helpless'],0],['The project was completed ___. (SUCCESS)',['success','successfully','successful'],1],['There is growing ___ about plastic waste. (AWARE)',['awareness','aware','unaware'],0]]},
{title:'Key word transformations',intro:'Choose the option with the same meaning.',qs:[['I last saw Mia three months ago.',['I haven’t seen Mia for three months.','I didn’t see Mia since three months.','I haven’t saw Mia for three months.'],0],['It wasn’t necessary for Leo to bring food.',['Leo mustn’t bring food.','Leo needn’t have brought food.','Leo didn’t need bringing food.'],1],['The test was so difficult that nobody finished.',['It was too difficult for anybody to finish the test.','It was enough difficult to finish.','Nobody finished because the test was easy.'],0]]}
];
function renderUoe(){const i=state.indices.uoe%uoeSets.length,s=uoeSets[i];uoeTitle.textContent=s.title;uoeCounter.textContent=`Challenge ${i+1} of ${uoeSets.length}`;uoeIntro.innerHTML=`<p>${s.intro}</p>`;uoeQuiz.innerHTML=s.qs.map((q,qi)=>`<fieldset class="panel"><legend>${qi+1}. ${q[0]}</legend>${q[1].length===1?`<input type="text" name="u${qi}" autocomplete="off">`:q[1].map((o,oi)=>`<label><input type="radio" name="u${qi}" value="${oi}"> ${o}</label>`).join('')}</fieldset>`).join('');uoeFeedback.textContent=''}
checkUoe.addEventListener('click',()=>{const s=uoeSets[state.indices.uoe%uoeSets.length],fd=new FormData(uoeQuiz);let score=0;s.qs.forEach((q,i)=>{const v=fd.get(`u${i}`);if(q[1].length===1){if(String(v||'').trim().toLowerCase()===q[1][0])score++}else if(Number(v)===q[2])score++});if(score===s.qs.length){completePractice('useofenglish',45);uoeFeedback.className='feedback success';uoeFeedback.textContent=`Perfect! ${score}/${s.qs.length}. +45 XP.`}else{uoeFeedback.className='feedback error';uoeFeedback.textContent=`You got ${score}/${s.qs.length}. Review the grammar pattern and try again.`}});
nextUoe.addEventListener('click',()=>{state.indices.uoe=(state.indices.uoe+1)%uoeSets.length;saveState();renderUoe()});

const cards=[['compelling','very convincing or interesting','The documentary presented a compelling argument.'],['reluctant','unwilling or hesitant','She was reluctant to speak in front of the class.'],['substantial','large or important','The project required a substantial amount of time.'],['take for granted','fail to appreciate something','We often take clean water for granted.'],['raise awareness','help people understand an issue','The campaign aims to raise awareness of food waste.'],['meet a deadline','finish work on time','The team worked late to meet the deadline.'],['highly unlikely','not expected to happen','It is highly unlikely that the event will be cancelled.'],['lasting impression','a strong memory or effect','The trip made a lasting impression on me.']];
let cardIndex=0,flipped=false;function renderCard(){const c=cards[cardIndex];cardWord.textContent=c[0];cardBack.innerHTML=`<strong>${c[1]}</strong><p>${c[2]}</p>`;cardBack.classList.toggle('hidden',!flipped);document.querySelector('#flashcard>span').classList.toggle('hidden',flipped)}function flip(){flipped=!flipped;renderCard()}flashcard.addEventListener('click',flip);flashcard.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();flip()}});nextCard.addEventListener('click',()=>{cardIndex=(cardIndex+1)%cards.length;flipped=false;renderCard()});prevCard.addEventListener('click',()=>{cardIndex=(cardIndex-1+cards.length)%cards.length;flipped=false;renderCard()});
const vocabQs=[['The speaker gave a very convincing argument. It was…',['compelling','reluctant','substantial'],'compelling'],['She did not really want to participate. She was…',['substantial','reluctant','compelling'],'reluctant'],['The campaign wants more people to understand the issue. It aims to…',['meet a deadline','raise awareness','take it for granted'],'raise awareness'],['The experience affected him for a long time. It made a…',['lasting impression','highly unlikely','deadline'],'lasting impression']];
function renderVocabQuiz(){const q=vocabQs[state.indices.vocabQuiz%vocabQs.length];vocabQuestion.textContent=q[0];vocabSelect.innerHTML='<option value="">Choose one</option>'+q[1].map(x=>`<option value="${x}">${x}</option>`).join('');vocabFeedback.textContent=''}
checkVocab.addEventListener('click',()=>{const q=vocabQs[state.indices.vocabQuiz%vocabQs.length],ok=vocabSelect.value===q[2];if(ok){completePractice('vocabulary',25);vocabFeedback.className='feedback success';vocabFeedback.textContent='Correct! +25 XP.'}else{vocabFeedback.className='feedback error';vocabFeedback.textContent='Not quite. Focus on meaning and collocation.'}});nextVocabQuiz.addEventListener('click',()=>{state.indices.vocabQuiz=(state.indices.vocabQuiz+1)%vocabQs.length;saveState();renderVocabQuiz()});

const connectorSets=[
[['The proposal was expensive. ___, it offered long-term benefits.',['Nevertheless','Therefore','For example'],'Nevertheless'],['The school improved its library. ___, it created new study spaces.',['In addition','Although','Consequently'],'In addition'],['The evidence was limited; ___, no final conclusion was reached.',['consequently','whereas','moreover'],'consequently']],
[['___ some students prefer online learning, others need face-to-face support.',['Whereas','Therefore','Furthermore'],'Whereas'],['The plan is practical. ___, it is affordable.',['Moreover','Even though','As a result of'],'Moreover'],['___ the weather was poor, the event continued.',['Even though','Consequently','In addition'],'Even though']]
];
function renderConnectors(){const i=state.indices.connectors%connectorSets.length,set=connectorSets[i];connectorsCounter.textContent=`Practice ${i+1} of ${connectorSets.length}`;connectorQuiz.innerHTML=set.map((q,qi)=>`<fieldset class="panel"><legend>${qi+1}. ${q[0]}</legend><select name="c${qi}"><option value="">Choose a connector</option>${q[1].map(o=>`<option value="${o}">${o}</option>`).join('')}</select></fieldset>`).join('');connectorFeedback.textContent=''}
checkConnectors.addEventListener('click',()=>{const set=connectorSets[state.indices.connectors%connectorSets.length],fd=new FormData(connectorQuiz);let score=0;set.forEach((q,i)=>{if(fd.get(`c${i}`)===q[2])score++});if(score===set.length){completePractice('connectors',35);connectorFeedback.className='feedback success';connectorFeedback.textContent=`Perfect! ${score}/${set.length}. +35 XP.`}else{connectorFeedback.className='feedback error';connectorFeedback.textContent=`You got ${score}/${set.length}. Think about the relationship between the ideas.`}});nextConnectors.addEventListener('click',()=>{state.indices.connectors=(state.indices.connectors+1)%connectorSets.length;saveState();renderConnectors()});

resetBtn.addEventListener('click',()=>{if(confirm('Reset all saved B2 progress on this device?')){state=structuredClone(defaultState);localStorage.removeItem(KEY);renderAll()}});
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove('hidden')});installBtn.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add('hidden')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));
function renderAll(){renderDashboard();renderDiagnostic();renderWriting();renderReading();renderUoe();renderCard();renderVocabQuiz();renderConnectors()}
renderAll();
